In [2]:
#es 1
#che tipo di struttura dati o matematica potrebbe rappresentare? Notare che tutte le liste "interne" sono della stessa dimensione 
#Come facciamo per accedere ad un elemento in particolare?


mat = [[0, 1, 2, 3, 4], 
       [5, 6, 7, 8, 9], 
       [10, 11, 12, 13, 14]]

#questa struttura dati ricorda una matrice
#visualizzandola come una matrice possiamo individare a posizione di un elemento specifico inserendo la riga e l colonna corrispondente

print(mat[1][3]) # 1 è la riga e 3 + la colonna di riferimento


8


In [3]:
import math
Sin = math.sin(81)
Cos = math.cos(225)
Fattoriale = math.factorial(5)
print(Sin)
print(Cos)
print(Fattoriale)

-0.6298879942744539
0.36731936773024515
120


In [4]:
math.degrees(math.pi)
#converte math.pi che sarebbe pigreco da radianti a gradi cio che ne cnsegue e questa formula: pigreco (radianti da convertire)/180 (gradi) * pi greco

180.0

In [25]:
# L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno: 
list = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]

#trasformiamola in un array NumPy (casting)
import numpy as np
arr_list = np.array(list)

#qual è stata la vendita massima mensile? E quella minima?
print(arr_list.max())
print(arr_list.min())

# quali sono le vendite mensili maggiori di 4999 oggetti? E quante ne sono? 
filtro = arr_list > 4999
print(arr_list[filtro])
print(arr_list[filtro].size)

# quali sono le vendite minori di 3000 oggetti? 
filtro_2 = arr_list < 3000
print(arr_list[filtro_2])

# in media quanti oggetti sono stati venduti al mese?
media = sum(arr_list)/len(arr_list)
print(media)

8150
1280
[5500 7200 6410 8150 7100 5350]
6
[2000 1280 1900 2500]
4634.166666666667


In [43]:
import pandas as pd
#Consideriamo il seguente dizionario: 
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000} 

#Consideriamo ora la seguente Series: 
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005)) 

#Possiamo accedere alle stesse informazioni nello stesso modo: 
fatturati_dict[1997] 
fatturati_series[1997] 

""" DOMANDA
Qual è la differenza tra i due tipi di dato? Cosa potremmo fare con la Series che non possiamo fare con il dizionario?

RISPOSTA
La differenza è che avendo importato pandas e utilizzando .series si ha una potenza di manipolazione dei dati molto maggiore rispetto al dizionario.
"""

' DOMANDA\nQual è la differenza tra i due tipi di dato? Cosa potremmo fare con la Series che non possiamo fare con il dizionario?\n\nRISPOSTA\nLa differenza è che avendo importato pandas e utilizzando .series si ha una potenza di manipolazione dei dati molto maggiore rispetto al dizionario.\n'

In [61]:
# ES
#L'azienda Object SpA ha un dataset con tutti gli stipendi dei dipendenti, memorizzato in un ndarray: 

import numpy as np 
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] )

for stipendio in stipendi:
    nuovo_stipendo = stipendi * 2
print(nuovo_stipendo)

stipendi * 2


[ 200  400  600  800 1000 1200 1400 1600 1800 2000]


array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])